quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=1234
quarkus.native.additional-build-args=-Dfile.encoding=UTF-8
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus-social
quarkus.datasource.jdbc.max-size=16

quarkus.smallrye-openapi.info-title=Minha API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Documentação da API
quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=Bearer Authentication
quarkus.smallrye-openapi.jwt-security-scheme-value=bearer
quarkus.smallrye-openapi.jwt-bearer-format=JWT
